# -*- coding: utf-8 -*-
"""Cópia de Student Performance Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjK4iVr271BuOoBhuKi4pKpLBqhTihxm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import classification_report, ConfusionMatrixDisplay

from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/student_dataset_10000_rows(1).csv')
display(df)

#verifica se há dados faltantes
nulos_por_coluna = df.isnull().sum()
print(nulos_por_coluna) # Mostra apenas as colunas que têm dados faltando

# definindo os limites de corte das notas.
# 0 a 70 (baixo), 70 a 90 (Mmdio), 90 a 100 (alto)
limites = [0, 70, 90, 100.1]
rotulos = ['Baixo', 'Médio', 'Alto']

df['faixa_rendimento'] = pd.cut(df['exam_score'], bins=limites, labels=rotulos)

print("Distribuição das Faixas de Rendimento:")
print(df['faixa_rendimento'].value_counts())

#definindo X e Y
X = df.drop(columns=['exam_score', 'faixa_rendimento', 'placement_status'])
Y = df['faixa_rendimento']

#codificando as variáveis categóricas em X
labelencoder_X = LabelEncoder()
for col in X.select_dtypes(include=['object', 'category']).columns:
    X[col] = labelencoder_X.fit_transform(X[col].astype(str))

#codificando Y para números
labelencoder_Y = LabelEncoder()
Y_encoded = labelencoder_Y.fit_transform(Y)

"""KNN com K-Fold"""

print("\n" + "="*60)
print("INICIANDO MODELO 1: KNN COM K-FOLD")
print("="*60)

# Padronização
sc_knn = StandardScaler()
X_knn = sc_knn.fit_transform(X)

# Definindo modelo KNN
knn = KNeighborsClassifier(n_neighbors=3, metric='euclidean')

#
n_splits = 5
kf = KFold(n_splits=n_splits, shuffle=True, random_state=42)

cvscores = []

for fold, (train_index, test_index) in enumerate(kf.split(X_knn), 1):
    print(f'\n*------------------- FOLD {fold} -------------------*')
    X_train_k, X_test_k = X_knn[train_index], X_knn[test_index]
    Y_train_k, Y_test_k = Y_encoded[train_index], Y_encoded[test_index]

    # Treinamento e Predição
    knn.fit(X_train_k, Y_train_k)
    y_pred_k = knn.predict(X_test_k)

    # Avaliação
    score = knn.score(X_test_k, Y_test_k)
    cvscores.append(score)
    print(classification_report(Y_test_k, y_pred_k, target_names=labelencoder_Y.classes_))

print(f"\n=> Acurácia em cada fold: {[round(s, 4) for s in cvscores]}")
print(f"=> Acurácia média do KNN: {np.mean(cvscores):.4f}")

"""SVM COM TRAIN/TEST SPLIT"""

#Divisão dos dados: 80% treino, 20% teste
X_train_svm, X_test_svm, Y_train_svm, Y_test_svm = train_test_split(X, Y_encoded, shuffle=True, test_size=0.2, random_state=42)

# Padronização
scaler_svm = StandardScaler()
X_train_svm = scaler_svm.fit_transform(X_train_svm)
X_test_svm = scaler_svm.transform(X_test_svm)

# Treinamento
clf = SVC(kernel='poly', gamma=0.5, C=100)
clf.fit(X_train_svm, Y_train_svm)

#Predição
y_pred_svm = clf.predict(X_test_svm)

print("\nRelatório de Classificação do SVM:")
print(classification_report(Y_test_svm, y_pred_svm, target_names=labelencoder_Y.classes_))

#matriz de confusão
fig, ax = plt.subplots(figsize=(6, 5))
ConfusionMatrixDisplay.from_predictions(
    Y_test_svm,
    y_pred_svm,
    display_labels=labelencoder_Y.classes_,
    cmap='Blues',
    ax=ax
)
plt.title('Matriz de Confusão - SVM')
plt.grid(False)
plt.show()

"""Random Forest"""

from sklearn.ensemble import RandomForestClassifier

#Definindo o modelo com 100 arvores de decisão
rf = RandomForestClassifier(n_estimators=100, random_state=42, class_weight='balanced')

# Garantindo que os dados de treino existam antes de treinar o Random Forest
# (Caso as células anteriores não tenham sido executadas)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1. Divisão dos dados
X_train_svm, X_test_svm, Y_train_svm, Y_test_svm = train_test_split(X, Y_encoded, shuffle=True, test_size=0.2, random_state=42)

# 2. Padronização
scaler_svm = StandardScaler()
X_train_svm = scaler_svm.fit_transform(X_train_svm)
X_test_svm = scaler_svm.transform(X_test_svm)

# 3. Treinamento do modelo Random Forest
rf.fit(X_train_svm, Y_train_svm)
print("✅ Modelo Random Forest treinado com sucesso!")

# Predição
y_pred_rf = rf.predict(X_test_svm)

# Relatório de Avaliação do Random Forest
print("\nRelatório de Classificação do Random Forest:")
print(classification_report(Y_test_svm, y_pred_rf, target_names=labelencoder_Y.classes_))

# Gerando a Matriz de Confusão do Random Forest
fig, ax = plt.subplots(figsize=(6, 5))
ConfusionMatrixDisplay.from_predictions(
    Y_test_svm,
    y_pred_rf,
    display_labels=labelencoder_Y.classes_,
    cmap='Greens',
    ax=ax
)
plt.title('Matriz de Confusão - Random Forest')
plt.grid(False)
plt.show()

import pickle

# Criando o dicionário com o modelo Random Forest (rf) que foi treinado com sucesso
dados_modelo = {
    'model': rf,              # Alterado de 'clf' para 'rf'
    'scaler': scaler_svm,      # scaler usado no treino
    'label_encoder': labelencoder_Y,
    'colunas': list(X.columns)
}

# Salva na raiz do Drive
with open('/content/drive/MyDrive/modelo_rf_alunos.pkl', 'wb') as f:
    pickle.dump(dados_modelo, f)

print("✅ Modelo Random Forest salvo no Drive!")
print("Colunas:", list(X.columns))
print("Classes:", list(labelencoder_Y.classes_))

"""# Teste Github e Streamlit"""

import os
import pandas as pd
import json
import pickle

# =====================================================================
# CONFIGURAÇÕES DO GITHUB
# =====================================================================
# COLE SEU TOKEN AQUI (Exemplo: GITHUB_TOKEN = "ghp_AbC123...")
GITHUB_TOKEN = "mindados"
GITHUB_USER = "LuanLindolfo"
REPO_NAME = "Mineracao_de_Dados"
EMAIL = "luan.lindolfo1211@gmail.com"

REPO_URL = f"https://{GITHUB_USER}:{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{REPO_NAME}.git"
REPO_PATH = f"/content/{REPO_NAME}"
# =====================================================================

# 1. Clonar ou Resetar Repositório
if not os.path.exists(REPO_PATH):
    print(f"📦 Clonando repositório...")
    os.system(f"git clone {REPO_URL} {REPO_PATH}")
else:
    print("🔄 Repositório já existe localmente.")

os.system(f'git config --global user.name "{GITHUB_USER}"')
os.system(f'git config --global user.email "{EMAIL}"')

# 2. Criar pastas dentro do repositório
path_results = os.path.join(REPO_PATH, 'data/results')
os.makedirs(path_results, exist_ok=True)

# 3. Salvar os arquivos DENTRO da pasta do repositório
try:
    # Salvando métricas JSON
    ml_results = {"modelo": "Random Forest", "acuracia": 0.74}
    json_path = os.path.join(path_results, 'ml_classificacao_metricas.json')
    with open(json_path, 'w') as f:
        json.dump(ml_results, f)

    # Salvando o modelo .pkl
    pkl_path = os.path.join(path_results, 'modelo_rf_alunos.pkl')
    with open(pkl_path, 'wb') as f:
        pickle.dump(dados_modelo, f)

    print(f"✅ Arquivos gravados em: {path_results}")

    # 4. Git Push - Forçando detecção de mudanças
    os.chdir(REPO_PATH)
    os.system("git add --all")

    mensagem = "Sincronização manual via Colab"
    commit_status = os.system(f'git commit -m "{mensagem}"')

    branch = os.popen("git branch --show-current").read().strip()
    print(f"Tentando Push na branch: {branch}")

    push_status = os.system(f"git push origin {branch}")

    if push_status == 0:
        print(f"🎉 SUCESSO! Verifique seu repositório online.")
    else:
        print("❌ FALHA NO PUSH: Verifique se o seu Token está correto e tem permissão de 'repo'.")

    os.chdir("/content")

except Exception as e:
    print(f"⚠️ Erro crítico: {e}")
    os.chdir("/content")

# Criando o app.py atualizado para o Random Forest e Streamlit Cloud
app_code = """import streamlit as st
import pickle
import numpy as np
import os

# 1. Configuração da Página
st.set_page_config(
    page_title="Previsão de Rendimento Escolar",
    page_icon="📊",
    layout="centered"
)

# 2. Carregar o Modelo e Objetos de Pré-processamento
@st.cache_resource
def carregar_modelo():
    # Caminho relativo baseado na pasta onde você salvou via GitHub no Colab
    caminho_modelo = 'data/results/modelo_rf_alunos.pkl'

    if not os.path.exists(caminho_modelo):
        st.error(f"⚠️ O arquivo '{caminho_modelo}' não foi encontrado. Verifique se o push para o GitHub funcionou.")
        st.stop()

    with open(caminho_modelo, 'rb') as f:
        data = pickle.load(f)

    return data['model'], data['scaler'], data['label_encoder']

# Inicializando o modelo
try:
    rf_model, scaler, labelencoder = carregar_modelo()
except Exception as e:
    st.error(f"Erro ao carregar os componentes do modelo: {e}")
    st.stop()

# 3. Cabeçalho da Interface
st.title("📊 Previsão de Rendimento Escolar")
st.markdown("### Random Forest — preencha os dados do aluno")
st.divider()

# 4. Criando o Layout (Grid 2x3)
col1, col2 = st.columns(2)

with col1:
    study_hours = st.number_input("Horas de estudo/dia", min_value=0.0, max_value=24.0, value=4.0, step=0.5)
    sleep_hours = st.number_input("Horas de sono/dia", min_value=0.0, max_value=24.0, value=7.0, step=0.5)
    assignments_completed = st.number_input("Tarefas entregues (%)", min_value=0.0, max_value=100.0, value=85.0, step=1.0)

with col2:
    attendance = st.number_input("Frequência (%)", min_value=0.0, max_value=100.0, value=90.0, step=1.0)
    internet_usage = st.number_input("Uso de internet (h/dia)", min_value=0.0, max_value=24.0, value=2.0, step=0.5)
    previous_score = st.number_input("Nota anterior (0–100)", min_value=0.0, max_value=100.0, value=75.0, step=1.0)

st.write("") # Espaçamento

# 5. Botão de Previsão e Lógica
if st.button("Prever Rendimento", use_container_width=True, type="primary"):
    # Organizando a entrada (Verifique se a ordem bate com X.columns do seu treino)
    dados = [study_hours, attendance, sleep_hours, internet_usage, assignments_completed, previous_score]
    entrada = np.array(dados).reshape(1, -1)

    # Transformação com o Scaler e Previsão
    entrada_scaled = scaler.transform(entrada)
    pred_num = rf_model.predict(entrada_scaled)[0]
    pred_label = labelencoder.inverse_transform([pred_num])[0]

    # 6. Exibição Dinâmica dos Resultados
    st.markdown("#### Resultado da Análise:")
    if pred_label == "Alto":
        st.success("🎉 Rendimento Alto")
    elif pred_label == "Médio":
        st.warning("📘 Rendimento Médio")
    elif pred_label == "Baixo":
        st.error("⚠️ Rendimento Baixo")
    else:
        st.info(f"Resultado: {pred_label}")
"""

requirements_code = """streamlit
numpy
scikit-learn
pandas
"""

# Salva os arquivos na raiz do Colab para você poder fazer o download ou enviá-los via Git depois
with open('app.py', 'w', encoding='utf-8') as f:
    f.write(app_code)

with open('requirements.txt', 'w', encoding='utf-8') as f:
    f.write(requirements_code)

print("✅ Arquivos 'app.py' e 'requirements.txt' gerados com sucesso na raiz do Colab!")

import os
import shutil
import glob
import json
from google.colab import userdata, _message

# --- FUNÇÃO DE SALVAMENTO AUTOMÁTICO ---
def preparar_notebook_para_envio(nome_arquivo="Cópia_de_Student_Performance_Prediction.ipynb"):
    try:
        res = _message.blocking_request('get_ipynb', request={}, timeout_sec=30)
        with open(f"/content/{nome_arquivo}", "w", encoding="utf-8") as f:
            json.dump(res['ipynb'], f, indent=4)
        print(f"💾 Notebook salvo localmente como {nome_arquivo}")
        return True
    except Exception as e:
        print(f"⚠️ Aviso: Não foi possível salvar o estado atual automaticamente: {e}")
        return False

# --- PROCESSO DE SINCRONIZAÇÃO ---
try:
    # 1. Garantir que o notebook atual foi salvo no /content com o nome correto
    nome_nb = "Cópia_de_Student_Performance_Prediction.ipynb"
    preparar_notebook_para_envio(nome_nb)

    # 2. Configurações
    TOKEN = userdata.get('mindados')
    USER = "LuanLindolfo"
    REPO = "Mineracao_de_Dados"
    BRANCH = "main"
    EMAIL = "luan.lindolfo1211@gmail.com"
    AUTH_URL = f"https://{USER}:{TOKEN}@github.com/{USER}/{REPO}.git"
    repo_path = f'/content/{REPO}'

    # 3. Clonar ou Atualizar Repositório
    if not os.path.exists(repo_path):
        print(f"📦 Clonando repositório {REPO}...")
        !git clone {AUTH_URL} {repo_path}
    else:
        os.chdir(repo_path)
        !git pull {AUTH_URL} {BRANCH}

    os.chdir(repo_path)
    !git config user.email "{EMAIL}"
    !git config user.name "{USER}"

    # 4. Copiar arquivos para a pasta do repositório
    os.chdir('/content')
    # Pegamos o notebook atualizado e os outros arquivos
    arquivos_alvo = [nome_nb, 'app.py', 'requirements.txt']

    for item in arquivos_alvo:
        if os.path.exists(item):
            shutil.copy(item, os.path.join(repo_path, item))
            print(f"✅ Arquivo '{item}' copiado para o repo.")

    # 5. Commit e Push
    os.chdir(repo_path)
    !git add .

    status = os.popen("git status --porcelain").read()
    if status:
        !git commit -m "update: atualizando notebook existente e arquivos"
        !git push {AUTH_URL} {BRANCH}
        print("🎉 SUCESSO! O notebook existente foi atualizado no GitHub.")
    else:
        print("✨ Nada para atualizar: o arquivo no GitHub já é o mesmo que o local.")

    os.chdir('/content')

except Exception as e:
    print(f"❌ Erro crítico: {e}")

import json
import os
from google.colab import _message

# Função para salvar o notebook atual como um arquivo .ipynb no /content
def salvar_notebook_local(nome_arquivo="Notebook_Mineracao.ipynb"):
    try:
        # Solicita ao Colab o conteúdo atual do notebook
        res = _message.blocking_request('get_ipynb', request={}, timeout_sec=30)
        with open(f"/content/{nome_arquivo}", "w", encoding="utf-8") as f:
            json.dump(res['ipynb'], f, indent=4)
        print(f"✅ Notebook salvo com sucesso em: /content/{nome_arquivo}")
    except Exception as e:
        print(f"❌ Erro ao salvar notebook: {e}")

salvar_notebook_local()